apiVersion: v1
kind: Secret
metadata:
  name: credentials
stringData:
  PG_CONNECTION_URL: jdbc:postgresql://postgresql/jboss
  PG_USERNAME: pguser
  PG_PASSWORD: pgpass
  KEYCLOAK: !!boolean true
  AUTH_URL: https://secure-sso-ntier.192.168.42.24.nip.io/auth
  PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAli9LDsEVLPAwgxskg4DWiTTDQsNvydMqrfygmvnUMemjXaG/ullY5sMVV0R5DHiJ5NMLnfAZTuKliefDY72Xx6n47bLDJRvu5MhZFMYch6NBG8IUmtezhSJ86t8Y4HWFZnsxfkuOtnv4jDedd88/TQbWggQxTRg70afCmgJbjFaTjIE8QIOQfUqIvrUZum6LOxttJFF8nDKCeRL/V4Ef1dfZaPX2BwAWmu6Uo7ZEjGU7JB5lNLkiHw4dRdgRuiuAKLRdzZuplEuvEYxhWR4qLciFPfUF8xwIKgEiU1+2p7hjcB8JCmyIfykZdVJEE8ctcoiXw8keKD+eBORYpQuG2wIDAQAB
